version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - sudo apt update
      - sudo apt install pipx
      - pipx ensurepath
      - pipx install poetry
      - poetry install

  pre_build:
    commands:
      - git clone --depth=1 --single-branch --branch=main https://github.com/aws/aws-cdk.git repositories/aws-cdk

  build:
    commands:
      - poetry run pytest tests/
      - poetry run python -m cdk_knowledge_extractor
